# Generated by Django 4.1.5 on 2023-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(max_length=250)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
