name: Deploy
on:
  push:
    branches:
        1 
          - main 
jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.10]
   
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@main
      with:
        host: 164.92.130.71
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd root/lebro
          source ./venv/bin/activate 
          git pull 
          python manage.py migrate 
          python manage.py collectstatic --noinput 
          supervisorctl restart all
